#! /bin/sh


. /lib/functions.sh
. /lib/functions/tlink.sh

failure_show() {
	for file in `ls /sys/class/leds/`; do
		if [ -d /sys/class/leds/$file ]; then
			if [ -f /sys/class/leds/$file/brightness ]; then
				echo "heartbeat" > /sys/class/leds/$file/trigger
			fi
		fi
	done
	while [ "1" = "1" ]; do
		sleep 1
	done
}

tlink_test() {
	mkdir -p /mnt/data/factory-tlink

	if [ -e /etc/init.d/symlink ]; then
		/etc/init.d/symlink stop
		/etc/init.d/symlink disable
	fi
	if [ -e /etc/init.d/skynet ]; then
		/etc/init.d/skynet stop
		/etc/init.d/skynet disable
	fi

	echo "Starting to doing factory make for board: $1" > /mnt/data/factory-tlink/tlink_test.log
	echo "Starting to doing factory make for board: $1" > /dev/console

	# Run test init script
	if [ -e /mnt/data/factory-tlink/test_run.sh ]; then
		sh /mnt/data/factory-tlink/test_run.sh
	else
		echo "No test script shell" > /dev/console
		echo "No test script shell" >> /mnt/data/factory-tlink/tlink_test.log
	fi

	if [ $? -ne 0 ]; then
		echo "TEST RUN FAILED!!!" > /dev/console
		echo "TEST RUN FAILED!!!" >> /mnt/data/factory-tlink/tlink_test.log
		failure_show
	fi

	echo "TEST RUN DONE!!!!!" > /dev/console
	echo "TEST RUN DONE!!!!!" >> /mnt/data/factory-tlink/tlink_test.log
}

case "$(board_name)" in
"kooiot,tlink-x1" | \
"kooiot,tlink-x3" | \
"kooiot,tlink-s1" | \
"kooiot,tlink-r1")
	# tlink_test_pre ${board_name}
	tlink_test ${board_name}
	;;
*)
	echo "UNKNOWN Board to do factory test!!!!" > /dev/console
	failure_show
	;;
esac
