#!/bin/sh
ip link set $INTERFACE up  
ip addr add 10.222.0.1/32 dev $INTERFACE

ip route add 10.222.0.2 dev $INTERFACE  proto kernel  scope link  src 10.222.0.1

ip route add 10.222.0.0/24 via 10.222.0.2 dev $INTERFACE

# iptables -A POSTROUTING -t nat -s 10.222.0.0/24 -j MASQUERADE -o eth0