# See /LICENSE for more information.
# This is free software, licensed under the GNU General Public License v2.

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for freeioe luci 
LUCI_DEPENDS:=+luci-base +luci-mod-status +freeioe

include ../../kooiot.mk

# call BuildPackage - OpenWrt buildroot signature
