#!/usr/bin/lua

local nixio = require 'nixio'

local function exec(cmd)
	local f, err = io.popen(cmd)
	if not f then
		return nil, err
	end
	local s = f:read('*a')
	f:close()
	return s
end

local function sysinfo_module()
	--print('sysinfo_module')

	local cmd = 'sysinfo module'
	local result = exec(cmd)
	if not result then
		return nil
	end
	
	local module = string.match(result, 'Modle:%s+([^%c]+)')
	local ccid = string.match(result, 'SimCard:%s+([^%c]+)')
	if ccid == 'UNKNOWN ERROR' then
		ccid = nil
	end
	--print('MODULE', module)
	--print('CCID', ccid)

	return {
		module = module,
		ccid = ccid
	}
end

local function echo_log(log)
	os.execute('echo "'..log..'" >> /dev/console')
	os.execute('echo "'..os.date()..': '..log..'" >> /root/wwanleds.log')
	os.execute('tail -n 500 /root/wwanleds.log > /root/wwanleds.log.new')
	os.execute('mv -f /root/wwanleds.log.new /root/wwanleds.log')
	os.execute("sync")
end

local function restart_wanpwrc()
	echo_log('4G Wan service restart')
	os.execute("/etc/init.d/wanpwrc restart")
end

local cloud_last = os.time()

local function watch_cloud_status()
	local now = os.time()

	local str, err = exec('cat /tmp/sysinfo/cloud_status')
	if str and string.len(str) > 0 then
		local status, last = string.match(str, '(%d+)%c+(%d+)')
		if status and last then
			if tonumber(status) == 1 then
				--- Use now when status is online (as the timestamp will be updated untill offline)
				cloud_last = now
			else
				--- offline timestamp will be updated, but we will not use it
				if cloud_last > now then
					cloud_last = now
				end
			end
		end
	else
		-- if file is empty, the programe is not running, skip checking
		cloud_last = now
	end
	--print(now, cloud_last)

	--- If 20 minutes that gateway not connected
	if now - cloud_last > 1200 then
		cloud_last = now
		echo_log('Cloud status out of date (20 min)')
		restart_wanpwrc()
	end
end

os.execute('touch /tmp/sysinfo/cloud_status') --- make sure the file is there
echo_log('Start wwanleds services...')

while true do
	local info = sysinfo_module()
	if info.module and info.ccid and string.len(info.ccid) > 0 then
		watch_cloud_status()
	end
	nixio.nanosleep(15)
end
