#!/usr/bin/lua

local nixio = require 'nixio'
local fs = require 'nixio.fs'
local json = require 'luci.jsonc'
local ss = require 'signalstrength'

local function exec(cmd)
	local f, err = io.popen(cmd)
	if not f then
		return nil, err
	end
	local s = f:read('*a')
	f:close()
	return s
end

local function exec_json(cmd)
	local result = exec(cmd)
	if not result then
		return nil
	end
	local parser = json.new()
	local r, err = parser:parse(result)
	if not r then
		return nil, err
	end

	return parser:get(), result
end

local function info_export(info)
	local f, err = io.open('/tmp/sysinfo/3ginfo')
	if not f then
		return nil, err
	end
	f:write(info)
	f:close()
end

local function led_control(info)
	--[[
	local sso = ss.new(info)
	local level = sso:level()

	if level >= 3 then
		os.execute("echo 1 > /sys/devices/platform/leds/leds/kooiot\\:green\\:gs/brightness")
		os.execute("echo 1 > /sys/devices/platform/leds/leds/kooiot\\:green\\:bs/brightness")
	else
		os.execute("echo 0 > /sys/devices/platform/leds/leds/kooiot\\:green\\:gs/brightness")
		if level >= 1  then
			os.execute("echo 1 > /sys/devices/platform/leds/leds/kooiot\\:green\\:bs/brightness")
		else
			os.execute("echo 0 > /sys/devices/platform/leds/leds/kooiot\\:green\\:bs/brightness")
		end
	end
	]]--

	local csq = info.csq or 0
	if csq >= 17 then
		os.execute("echo 1 > /sys/devices/platform/leds/leds/kooiot\\:green\\:gs/brightness")
		os.execute("echo 1 > /sys/devices/platform/leds/leds/kooiot\\:green\\:bs/brightness")
	else
		os.execute("echo 0 > /sys/devices/platform/leds/leds/kooiot\\:green\\:gs/brightness")
		if csq >= 10  then
			os.execute("echo 1 > /sys/devices/platform/leds/leds/kooiot\\:green\\:bs/brightness")
		else
			os.execute("echo 0 > /sys/devices/platform/leds/leds/kooiot\\:green\\:bs/brightness")
		end
	end

end

while true do
	local info, info_str = exec_json('3ginfo json')
	info_export(info_str)
	led_control(info)	
	nixio.nanosleep(15)
end
