#!/bin/sh /etc/rc.common
# Copyright (C) 2019-2020 Dirk Chang

START=21
STOP=90

USE_PROCD=1

start_service () {
	procd_open_instance
	procd_set_param command cloud_watch
	procd_set_param respawn
	procd_close_instance
}

