#! /bin/sh


. /lib/functions.sh
. /lib/functions/tlink.sh

failure_show() {
	for file in `ls /sys/class/leds/`; do
		if [ -d /sys/class/leds/$file ]; then
			if [ -f /sys/class/leds/$file/brightness ]; then
				echo "heartbeat" > /sys/class/leds/$file/trigger
			fi
		fi
	done
	while [ "1" = "1" ]; do
		echo "ERROR" > /dev/console
		sleep 1
	done
}

tlink_make_pre() {
	local MACADDR
	export_tlink_efuse MACADDR 2 || {
		return
	}
	ifconfig eth1 down
	ifconfig eth1 hw ether ${MACADDR}
	ifconfig eth1 up
}

tlink_make() {
	echo "Starting to doing factory make for board: $1" > /tmp/tlink_make.log
	echo "Starting to doing factory make for board: $1" > /dev/console

	/sbin/install_to_emmc -f


	if [ $? -ne 0 ]; then
		echo "INSTALL FAILED!!!" > /dev/console
		echo "INSTALL FAILED!!!" >> /tmp/tlink_make.log
		failure_show
	fi

	echo "INSTALL OS DONE!!!!!" > /dev/console
	echo "INSTALL OS DONE!!!!!" >> /tmp/tlink_make.log

	echo "Start FreeIOE for hwtest" > /dev/console
	echo "Start FreeIOE for hwtest" >> /tmp/tlink_make.log

	cd /usr/ioe/skynet

	export IOE_HWTEST_FINISH_HALT=1
	./skynet ioe/hwtest_config

	if [ $? -ne 0 ]; then
		echo "HWTEST START FAILED!!!" > /dev/console
		echo "HWTEST START FAILED!!!" >> /tmp/tlink_make.log
		failure_show
	fi
}

case "$(board_name)" in
"kooiot,tlink-x1" | \
"kooiot,tlink-r1")
	tlink_make_pre ${board_name}
	tlink_make ${board_name}
	;;
*)
	echo "UNKNOWN Board to do factory make!!!!" > /dev/console
	failure_show
	;;
esac
