#!/bin/sh

. /lib/functions.sh

board=$(board_name)

# logger -t hotplug $(env)

tlink_android_gen_conf() {
	# logger -t hotplug $(env)
	RNDIS_CHK="RNDIS Communications Control"
	if [ ! -f /sys$DEVPATH/../../interface ]; then
		return
	fi

	intf=$(cat /sys$DEVPATH/../../interface)

	echo "Android Check: ""${intf}" > /dev/kmsg

	if [ "${intf}"x = "${RNDIS_CHK}"x ]; then
		logger -t hotplug "Android USB Ethernet found! Name: ${DEVICE_NAME} Interface: ${INTERFACE}"
		uci set network.android_usb='interface'
		uci set network.android_usb.proto='dhcp'
		uci set network.android_usb.device=${INTERFACE}
		uci commit network

		# firewall
		# wan_network=`uci get firewall.@zone[1].network`
		# uci set firewall.@zone[1].network="$wan_network android_usb"
		# uci commit firewall

		sh -c "sleep 3 && ifdown android_usb && sleep 1 && ifup android_usb" &
	fi
}

[ "$ACTION" = add ] && {
	tlink_android_gen_conf
}

[ "$ACTION" = remove ] && {
	if [ "$(uci get network.android_usb.device)" = "${INTERFACE}" ]; then
		logger -t hotplug "Android USB Ethernet removed found! Name: ${DEVICE_NAME} Interface: ${INTERFACE}"
		uci del network.android_usb
		uci commit network
	fi
}
