#! /bin/sh


. /lib/functions.sh
. /lib/functions/tlink.sh

install_show() {
	for file in `ls /sys/class/leds/`; do
		if [ -d /sys/class/leds/$file ]; then
			if [ -f /sys/class/leds/$file/brightness ]; then
				echo "default-on" > /sys/class/leds/$file/trigger
			fi
		fi
	done
}

failure_show() {
	for file in `ls /sys/class/leds/`; do
		if [ -d /sys/class/leds/$file ]; then
			if [ -f /sys/class/leds/$file/brightness ]; then
				echo "heartbeat" > /sys/class/leds/$file/trigger
			fi
		fi
	done
	while [ "1" = "1" ]; do
		sleep 1
	done
}

tlink_make_pre() {
	local MACADDR
	export_tlink_efuse MACADDR 2 || {
		return
	}
	ifconfig eth1 down
	ifconfig eth1 hw ether ${MACADDR}
	ifconfig eth1 up
}

tlink_make() {
	echo "Starting to doing factory make for board: $1" > /dev/kmsg
	echo "Starting to doing factory make for board: $1" > /tmp/tlink_make.log

	install_show

	/sbin/install_to_emmc -f

	if [ $? -ne 0 ]; then
		echo "INSTALL FAILED!!!" > /dev/kmsg
		echo "INSTALL FAILED!!!" >> /tmp/tlink_make.log
		failure_show
	fi

	if [ -e /mnt/factory-tlink ]; then
		mkdir -p /mnt/data
		mount /dev/mmcblk1p3 /mnt/data
		if [ $? -ne 0 ]; then
			echo "MOUNT FAILED!!!" > /dev/kmsg
			echo "MOUNT FAILED!!!" >> /tmp/tlink_make.log
			failure_show
		fi

		mkdir -p /mnt/data/factory-tlink
		cp -fpR /mnt/factory-tlink /mnt/data/
		sync

		echo "INSTALL OS DONE!!!!!" > /dev/kmsg
		echo "INSTALL OS DONE!!!!!" >> /tmp/tlink_make.log
		halt
	else
		echo "FACTORY FILES MISSING !!!" > /dev/kmsg
		echo "FACTORY FILES MISSING !!!" >> /tmp/tlink_make.log
		failure_show
	fi
}

case "$(board_name)" in
"kooiot,tlink-x1" | \
"kooiot,tlink-x1s" | \
"kooiot,tlink-x3" | \
"kooiot,tlink-s1" | \
"kooiot,tlink-k1" | \
"kooiot,tlink-k2" | \
"kooiot,tlink-k2x" | \
"kooiot,tlink-m408" | \
"kooiot,tlink-m416" | \
"kooiot,tlink-r1")
	# tlink_make_pre ${board_name}
	tlink_make ${board_name}
	;;
*)
	echo "UNKNOWN Board to do factory make!!!!" > /dev/kmsg
	failure_show
	;;
esac
