#! /bin/sh


. /lib/functions.sh
. /lib/functions/tlink.sh

install_show() {
	for file in `ls /sys/class/leds/`; do
		if [ -d /sys/class/leds/$file ]; then
			if [ -f /sys/class/leds/$file/brightness ]; then
				echo "default-on" > /sys/class/leds/$file/trigger
			fi
		fi
	done
}

failure_show() {
	for file in `ls /sys/class/leds/`; do
		if [ -d /sys/class/leds/$file ]; then
			if [ -f /sys/class/leds/$file/brightness ]; then
				echo "heartbeat" > /sys/class/leds/$file/trigger
			fi
		fi
	done
	while [ "1" = "1" ]; do
		echo "ERROR" > /dev/console
		sleep 1
	done
}

tlink_make_pre() {
	local MACADDR
	export_tlink_efuse MACADDR 2 || {
		return
	}
	ifconfig eth1 down
	ifconfig eth1 hw ether ${MACADDR}
	ifconfig eth1 up
}

tlink_make() {
	echo "Starting to doing factory make for board: $1" > /tmp/tlink_make.log
	echo "Starting to doing factory make for board: $1" > /dev/console

	install_show

	/sbin/install_to_emmc -f

	if [ $? -ne 0 ]; then
		echo "INSTALL FAILED!!!" > /dev/console
		echo "INSTALL FAILED!!!" >> /tmp/tlink_make.log
		failure_show
	fi

	if [ -e /mnt/factory_tlink ]; then
		mkdir -p /mnt/data
		mount /dev/mmcblk1p3 /mnt/data
		if [ $? -eq 0 ]; then
			echo "INSTALL FAILED!!!" > /dev/console
			echo "INSTALL FAILED!!!" >> /tmp/tlink_make.log
			failure_show
		fi
		mkdir -p /mnt/data/factory_tlink
		cp -fpR /mnt/factory_tlink /mnt/data/
		sync
	fi

	echo "INSTALL OS DONE!!!!!" > /dev/console
	echo "INSTALL OS DONE!!!!!" >> /tmp/tlink_make.log
	# halt
}

case "$(board_name)" in
"kooiot,tlink-x1" | \
"kooiot,tlink-x3" | \
"kooiot,tlink-s1" | \
"kooiot,tlink-r1")
	# tlink_make_pre ${board_name}
	tlink_make ${board_name}
	;;
*)
	echo "UNKNOWN Board to do factory make!!!!" > /dev/console
	failure_show
	;;
esac
