#! /bin/sh


. /lib/functions.sh
. /lib/functions/tlink.sh

install_show() {
	for file in `ls /sys/class/leds/`; do
		if [ -d /sys/class/leds/$file ]; then
			if [ -f /sys/class/leds/$file/brightness ]; then
				echo "default-on" > /sys/class/leds/$file/trigger
			fi
		fi
	done
}

failure_show() {
	for file in `ls /sys/class/leds/`; do
		if [ -d /sys/class/leds/$file ]; then
			if [ -f /sys/class/leds/$file/brightness ]; then
				echo "heartbeat" > /sys/class/leds/$file/trigger
			fi
		fi
	done
	while [ "1" = "1" ]; do
		sleep 1
	done
}

tlink_make_pre() {
	local MACADDR
	export_tlink_efuse MACADDR 2 || {
		return
	}
	ifconfig eth1 down
	ifconfig eth1 hw ether ${MACADDR}
	ifconfig eth1 up
}

tlink_mkfs_storage() {
	local BOARD_NAME=$1
	local STORAGE_DISK="/dev/sda"
	if [ -b ${STORAGE_DISK} ]; then
		echo "Creating Storage Disk partitions" > /dev/kmsg
		echo "Creating Storage Disk partitions" >> /tmp/tlink_make.log

		echo -e "n\np\n1\n2048\n\nw" | fdisk ${STORAGE_DISK} > /dev/null 2>&1
		sync
		sleep 2
		partx -s ${STORAGE_DISK} > /dev/null 2>&1
		if [ $? -ne 0 ]; then
			echo "ERROR: Failed to create storage disk partition" > /dev/kmsg
			echo "ERROR: Failed to create storage disk partition" >> /tmp/tlink_make.log
			exit 1
		fi
		sleep 1
		if [ ! -b ${STORAGE_DISK}1 ]; then
			echo "ERROR: Failed to find storage disk partition" > /dev/kmsg
			echo "ERROR: Failed to find storage disk partition" >> /tmp/tlink_make.log
			exit 1
		fi

		mkfs.ext4 -L storage ${STORAGE_DISK}1 > /dev/null 2>&1
		if [ $? -ne 0 ]; then
			echo "ERROR: Failed to formate storage disk partition" > /dev/kmsg
			echo "ERROR: Failed to formate storage disk partition" >> /tmp/tlink_make.log
			exit 1
		fi
	else
		echo "Board has no storage disk: ${BOARD_NAME}" > /dev/kmsg
		echo "Board has no storage disk: ${BOARD_NAME}" >> /tmp/tlink_make.log
	fi
}

tlink_make() {
	local BOARD_NAME=$1
	echo "Starting to doing factory make for board: ${BOARD_NAME}" > /dev/kmsg
	echo "Starting to doing factory make for board: ${BOARD_NAME}" >> /tmp/tlink_make.log

	install_show

	/sbin/install_to_emmc -f > /dev/kmsg 2>&1

	if [ $? -ne 0 ]; then
		echo "INSTALL FAILED!!!" > /dev/kmsg
		echo "INSTALL FAILED!!!" >> /tmp/tlink_make.log
		failure_show
	fi

	if [ -e /mnt/factory-tlink ]; then
		mkdir -p /mnt/data
		mount /dev/mmcblk1p3 /mnt/data
		if [ $? -ne 0 ]; then
			echo "MOUNT FAILED!!!" > /dev/kmsg
			echo "MOUNT FAILED!!!" >> /tmp/tlink_make.log
			failure_show
		fi

		mkdir -p /mnt/data/factory-tlink
		cp -fpR /mnt/factory-tlink /mnt/data/
		sync

		echo "INSTALL OS DONE!!!!!" > /dev/kmsg
		echo "INSTALL OS DONE!!!!!" >> /tmp/tlink_make.log
		halt
	else
		echo "FACTORY FILES MISSING !!!" > /dev/kmsg
		echo "FACTORY FILES MISSING !!!" >> /tmp/tlink_make.log
		failure_show
	fi
}

case "$(board_name)" in
"kooiot,tlink-x1" | \
"kooiot,tlink-x1s" | \
"kooiot,tlink-x3" | \
"kooiot,tlink-s1" | \
"kooiot,tlink-k1" | \
"kooiot,tlink-k2" | \
"kooiot,tlink-k2x" | \
"kooiot,tlink-e1" | \
"kooiot,tlink-m408" | \
"kooiot,tlink-m416" | \
"kooiot,tlink-r1")
	# tlink_make_pre ${board_name}
	tlink_make $(board_name)
	;;
"kooiot,tlink-r4x" | \
"kooiot,tlink-r7" | \
"kooiot,tlink-r1")
	tlink_mkfs_storage $(board_name)
	tlink_make $(board_name)
	;;	
*)
	echo "UNKNOWN Board to do factory make!!!!" > /dev/kmsg
	failure_show
	;;
esac
