#!/bin/sh /etc/rc.common
# Copyright (C) 2017 symid.com

START=99


start () {
	tincd -n symbridge
}

stop () {
	tincd -n symbridge -k
}

restart () {
	tincd -n symbridge -k
	sleep 1
	tincd -n symbridge
}
