#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

NAME=robot-client
PROG=/usr/bin/$NAME
CONF_FILE=/etc/robot/client/config.yaml

_err() {
	echo "$*" >&2
	logger -p daemon.err -t "$NAME" "$*"
}

start_service() {
	local init_cfg=" "

	procd_open_instance
	procd_set_param command "$PROG" -c "$CONF_FILE"
	procd_set_param stdout $stdout
	procd_set_param stderr $stderr
	[ $respawn -eq 1 ] && procd_set_param respawn
	procd_close_instance
}
