#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

NAME=robot-pong
PROG=/usr/bin/$NAME
CONF_FILE=/etc/robot/robot-pong/config.yaml
WORK_DIR=/var/robot

_err() {
	echo "$*" >&2
	logger -p daemon.err -t "$NAME" "$*"
}

start_service() {
	mkdir -p $WORK_DIR

	procd_open_instance
	procd_set_param command "$PROG" -c "$CONF_FILE" -d "$WORK_DIR"
	procd_set_param stdout $stdout
	procd_set_param stderr $stderr
	procd_set_param respawn
	procd_close_instance
}
