#!/bin/sh /etc/rc.common
# Copyright (C) 2023 Dirk Chang

START=89
STOP=90

USE_PROCD=1

start_service () {
	procd_open_instance
	procd_set_param command xr_usb_watch
	procd_set_param respawn
	procd_close_instance
}

